[package]
name = "kern"
version = "1.1.4"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2018"
license = "ISC"
repository = "https://github.com/ltheinrich/kern"
description = "General library for Rust"
readme = "README.md"
